name: mechat_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  azlistview: ^0.1.2
  lpinyin: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_launcher_icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/tabbar_contacts@3x.png
    - assets/icon/tabbar_contactsHL@3x.png
    - assets/icon/tabbar_discover@3x.png
    - assets/icon/tabbar_discoverHL@3x.png
    - assets/icon/tabbar_mainframe@3x.png
    - assets/icon/tabbar_mainframeHL@3x.png
    - assets/icon/tabbar_me@3x.png
    - assets/icon/tabbar_meHL@3x.png
    - assets/images/pi.jpg
    - assets/images/ic_collections.png
    - assets/images/ic_settings.png
    - assets/images/wechat-pay-line.png
    - assets/images/ic_album.png
    - assets/data/contacts.json
    - assets/images/ic_group_chat.png
    - assets/images/ic_new_friend.png
    - assets/images/ic_official_account.png
    - assets/images/ic_tag.png
    - assets/images/loading.jpg
    - assets/avartar/a001.jpg
    - assets/avartar/a002.png
    - assets/avartar/a003.jpg
    - assets/avartar/a004.jpg
    - assets/avartar/a005.jpg
    - assets/avartar/a006.jpg
    - assets/avartar/a007.jpg
    - assets/avartar/a008.jpg

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/launcher_icon3.png"

